// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperViagemAPI.Data;

#nullable disable

namespace SuperViagemAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240107015949_fmigration")]
    partial class fmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SuperViagemAPI.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("usuario_email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("usuario_nome");

                    b.Property<string>("UsuarioURL")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("usuarioURL");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("usuario_senha");

                    b.HasKey("Id");

                    b.ToTable("usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jose.pedro@gmail.com",
                            Nome = "José Pedro",
                            UsuarioURL = "hhtps://www.jose123.com",
                            senha = "jose123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "victor.diniz@gmail.com",
                            Nome = "Victor Diniz",
                            UsuarioURL = "hhtps://www.jose123.com",
                            senha = "victor123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "agnaldo.ribeiro@gmail.com",
                            Nome = "Agnaldo Ribeiro",
                            UsuarioURL = "hhtps://www.jose123.com",
                            senha = "agnaldo123"
                        },
                        new
                        {
                            Id = 4,
                            Email = "pamela.lucia@gmail.com",
                            Nome = "Pamela Lucia",
                            UsuarioURL = "hhtps://www.jose123.com",
                            senha = "pamela123"
                        },
                        new
                        {
                            Id = 5,
                            Email = "maria.ferraz@gmail.com",
                            Nome = "Maria Ferraz",
                            UsuarioURL = "hhtps://www.jose123.com",
                            senha = "maria123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
